### ISSUE TITLE
Make Botch with more scratch logic

### ISSUE THREAD

**Issue by raffaelepojer** [CoderDojoTrento/botch-vm#19]
In this issue, there will be referenced all the possible ways to make Botch more "scratchable".

Examples: 

- One aspect is to treat new organism as a proper clone in scratch
 ![image](https://user-images.githubusercontent.com/18617911/90258434-dde4ea80-de48-11ea-9965-595c63087311.png)

- Instead of having a long list, of probably useless variable, use a list to select the type of variable to view
 ![image](https://user-images.githubusercontent.com/18617911/90258806-58156f00-de49-11ea-8388-7914070802bf.png)

**Comment by raffaelepojer** [comment]
![image](https://user-images.githubusercontent.com/18617911/90260734-379ae400-de4c-11ea-823a-bbf9061b379c.png)
Anther possible block (now useless)

**Comment by raffaelepojer** [comment]
This kind of blocks are not intuitive, I think is better to do It manually on scratch using core blocks
![image](https://user-images.githubusercontent.com/18617911/90261875-da079700-de4d-11ea-9f99-45393ff73eb4.png)
One possible implementation with food could be like that:
![image](https://user-images.githubusercontent.com/18617911/90262397-906b7c00-de4e-11ea-8e9f-6066910ab893.png)

**Comment by raffaelepojer** [comment]
Same thing with enemies:
![image](https://user-images.githubusercontent.com/18617911/90262980-50f15f80-de4f-11ea-89b9-07761a0dccb4.png)

Maybe move enemy could be "attack organism"

**Comment by raffaelepojer** [comment]
Add hat blocks, such as: "When an organism die" or "When an organism is confuse"
![image](https://user-images.githubusercontent.com/18617911/90263529-150aca00-de50-11ea-8c71-ca317344198d.png)

**Comment by raffaelepojer** [comment]
> This kind of blocks are not intuitive, I think is better to do It manually on scratch using core blocks
> ![image](https://user-images.githubusercontent.com/18617911/90261875-da079700-de4d-11ea-9f99-45393ff73eb4.png)
> One possible implementation with food could be like that:
> ![image](https://user-images.githubusercontent.com/18617911/90262397-906b7c00-de4e-11ea-8e9f-6066910ab893.png)

Since that food it's only a clone of a sprite, it is possible to retrieve all the required from the original and its clones
![image](https://user-images.githubusercontent.com/18617911/90265429-df1b1500-de52-11ea-8b6e-b43d0f82ac8f.png)

**Comment by raffaelepojer** [comment]
**In conclusion** 

- Use **set as [_type_]** with a drop down menu for: Organism, Food, Poison, Enemy

- **generate n children** will be used for: Organism and Enemy

- Food and poison as [the comment above](https://github.com/CoderDojoTrento/botch-vm/issues/19#issuecomment-674127706)

Examples:

![image](https://user-images.githubusercontent.com/18617911/90269723-5bb0f200-de59-11ea-9488-f750a33609c1.png)

**Comment by raffaelepojer** [comment]
Each time the block "**set as organism**" is active it should delete all the previous organism's costumes

**Comment by DavidLeoni** [comment]
> Each time the block "**set as organism**" is active it should delete all the previous organism's costumes

Careful about deletion - what if the user changed those costumes? Is there some flag to know it?

**Comment by raffaelepojer** [comment]
> > Each time the block "**set as organism**" is active it should delete all the previous organism's costumes
> 
> Careful about deletion - what if the user changed those costumes? Is there some flag to know it?

Only sprites starting with "_org" will be deleted, in this way the costumes that are loaded by the user will not be deleted. Unless you want to call them that way ...
